#!/usr/bin/env python3

import sys
import argparse
import hashlib
import zlib

parser = argparse.ArgumentParser()
parser.add_argument('string', help='String to encrypt')
args = parser.parse_args()

separator = '##################################################'

print(separator)

print('STRING: ', args.string)
print('MD5:    ', hashlib.md5(args.string.encode('utf-8')).hexdigest())
print('SHA1:   ', hashlib.sha1(args.string.encode('utf-8')).hexdigest())
print('SHA224: ', hashlib.sha224(args.string.encode('utf-8')).hexdigest())
print('SHA256: ', hashlib.sha256(args.string.encode('utf-8')).hexdigest())
print('SHA384: ', hashlib.sha384(args.string.encode('utf-8')).hexdigest())
print('SHA512: ', hashlib.sha512(args.string.encode('utf-8')).hexdigest())
print('CRC32:  ', hex(zlib.crc32(args.string.encode('utf-8'))))
print('ADLER32:', hex(zlib.adler32(args.string.encode('utf-8'))))

print(separator)

